/**
 * Bundle the extension into a dist directory.
 *   - manifest.json  (patched: content_scripts, optional CSP rules, browser target)
 *   - inject.js, popup.{html,css,js} (from src/)
 *   - icon-{16,32,48,128}.png (generated by icon.js)
 *   - csp-rules.json (generated from sites with a `csp` field, if any)
 *
 * dappfence.js is NOT bundled — the content script loads it from the site's own
 * origin (/dappfence.js) so the service worker can verify it against the manifest.
 *
 * Importable:
 *   import { build } from './build.js';
 *   build({ target, dist, sites });
 *
 * CLI:
 *   node build.js                              → Chrome, dist/
 *   node build.js --target=firefox             → Firefox, dist/
 *   node build.js --dist=dist-test --sites=... → custom output and sites list
 *
 * sites accepts strings or objects:
 *   "https://app.uniswap.org/*"
 *   { "pattern": "https://app.aave.com/*", "csp": "...", "manifest": "/integrity-manifest.json",
 *     "signatureType": "noble-secp256k1-recovered-eth", "signatureIdentity": "0x..." }
 */

import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateIcons } from './icon.js';

const here = dirname(fileURLToPath(import.meta.url));

/**
 * @param {object}       opts
 * @param {'chrome'|'firefox'} [opts.target='chrome']
 * @param {string}       [opts.dist]  - Output directory. Defaults to <here>/dist.
 * @param {Array}        opts.sites   - Site entries: plain URL strings or
 *                                     { pattern, csp?, manifest?, signatureType?, signatureIdentity? } objects.
 */
export function build({ target = 'chrome', dist = join(here, 'dist'), sites } = {}) {
    rmSync(dist, { recursive: true, force: true });
    mkdirSync(dist, { recursive: true });

    const manifest = JSON.parse(readFileSync(join(here, 'src', 'manifest.json'), 'utf8'));

    // Normalise to { pattern, csp?, manifest?, signatureType?, signatureIdentity? } objects.
    const siteEntries = sites.map((entry) =>
        typeof entry === 'string' ? { pattern: entry } : entry
    );

    const patterns = siteEntries.map((s) => s.pattern);
    const cspSites = siteEntries.filter((s) => s.csp);

    // Exclude DappFence's own /sw-api/* pages (security warning, status, etc.) so
    // the content script is never injected there. Without this exclusion the SW
    // returns a JS-redirect response for /dappfence.js while the site is blocked,
    // which causes an infinite redirect loop on the security warning page.
    const swApiExcludes = patterns.map((p) => p.replace(/\*$/, 'sw-api/*'));

    manifest.content_scripts = [
        {
            matches: patterns,
            exclude_matches: swApiExcludes,
            js: ['inject.js'],
            run_at: 'document_start',
            all_frames: false,
        },
    ];

    if (cspSites.length > 0) {
        const cspRules = cspSites.map((site, i) => ({
            id: i + 1,
            priority: 1,
            action: {
                type: 'modifyHeaders',
                responseHeaders: [
                    { header: 'Content-Security-Policy', operation: 'set', value: site.csp },
                ],
            },
            condition: {
                // "|" prefix = URL must start with this string (DNR syntax).
                urlFilter: `|${site.pattern.replace('*', '')}`,
                resourceTypes: ['main_frame'],
            },
        }));

        writeFileSync(join(dist, 'csp-rules.json'), JSON.stringify(cspRules, null, 4));
        manifest.permissions.push('declarativeNetRequest');
        manifest.host_permissions = cspSites.map((s) => s.pattern);
        manifest.declarative_net_request = {
            rule_resources: [{ id: 'csp_rules', enabled: true, path: 'csp-rules.json' }],
        };
    }

    if (target === 'firefox') {
        manifest.browser_specific_settings = {
            gecko: { id: '@dappfence', strict_min_version: '127.0' },
        };
    }

    writeFileSync(join(dist, 'manifest.json'), JSON.stringify(manifest, null, 4));

    // Build per-origin dappfence config map and prepend it to inject.js.
    const siteConfigMap = {};
    for (const entry of siteEntries) {
        if (entry.manifest || entry.signatureType || entry.signatureIdentity) {
            const origin = entry.pattern.replace(/\/\*.*$/, '').replace(/\/$/, '');
            siteConfigMap[origin] = {
                ...(entry.manifest && { manifest: entry.manifest }),
                ...(entry.signatureType && { signatureType: entry.signatureType }),
                ...(entry.signatureIdentity && { signatureIdentity: entry.signatureIdentity }),
            };
        }
    }
    const injectSrc = readFileSync(join(here, 'src', 'inject.js'), 'utf8');
    writeFileSync(
        join(dist, 'inject.js'),
        `const SITE_CONFIG = ${JSON.stringify(siteConfigMap)};\n${injectSrc}`
    );

    for (const file of ['background.js', 'popup.html', 'popup.css', 'popup.js']) {
        copyFileSync(join(here, 'src', file), join(dist, file));
    }
    generateIcons(dist);

    console.log(`[extension] built ${dist}`);
}

// --- CLI entry point ---

if (process.argv[1] === fileURLToPath(import.meta.url)) {
    const target = process.argv.includes('--target=firefox') ? 'firefox' : 'chrome';
    const distArg = process.argv.find((a) => a.startsWith('--dist='));
    const sitesArg = process.argv.find((a) => a.startsWith('--sites='));
    const sitesPath = sitesArg
        ? join(here, sitesArg.slice('--sites='.length))
        : join(here, 'src', 'sites.json');

    build({
        target,
        dist: distArg ? join(here, distArg.slice('--dist='.length)) : undefined,
        sites: JSON.parse(readFileSync(sitesPath, 'utf8')),
    });
}
